AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - db/**/*
    - config/**/*
    - vendor/**/*
    - Gemfile

Style/FrozenStringLiteralComment:
  Enabled: false